version: '3.3'
services:
  geth:
    image: ethereum/client-go:v1.12.0
    environment:
      - DEV_PERIOD
    ports:
      - '8545:8545'
    volumes:
      - ./geth_db:/geth_db
    entrypoint:
      - geth
      - --rpc.allow-unprotected-txs
      - --http
      - --http.addr
      - '0.0.0.0'
      - --dev
      - --dev.period
      - $DEV_PERIOD
      - --gcmode
      - archive
      - --datadir
      - /geth_db
